language: haxe

os:
  - linux
  - osx

sudo: false
dist: trusty

haxe:
  - "3.4.7"
  - development

addons:
  apt:
    packages:
      # C++
      - gcc-multilib
      - g++-multilib
      # Python
      - python3
      # C#
      - mono-devel
      - mono-mcs
      # Flash
      - libglib2.0
      - libfreetype6

install:
  # os-specific config
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      export DISPLAY=:99.0;
      export AUDIODEV=null;
      phpenv global 7.0;
    elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update;
      brew install mono;
      brew upgrade python;
      brew install php;
    fi
  # Download and setup a standalone flash player debugger
  - haxe flash/install.hxml
  # Install haxelibs
  - if [ "${TRAVIS_HAXE_VERSION}" = "development" ]; then
      haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp.git;
    else
      haxelib install hxcpp;
    fi
  - if [ "${TRAVIS_HAXE_VERSION}" = "development" ] || [ "${TRAVIS_HAXE_VERSION}" = "3.2.1" ]; then
      pushd $(haxelib path hxcpp | head -1);
        pushd tools/hxcpp; haxe compile.hxml; popd;
        pushd project; neko build.n; popd;
      popd;
    fi
  - haxelib install hxjava
  - haxelib install hxcs
  - haxelib install hx3compat
  - haxelib dev hscript .
  - haxelib list

script:
  - pushd script &&
    haxe build.hxml &&
    popd
  - haxe bin/build-interp.hxml
  - haxe bin/build-interp.hxml -D hscriptPos
  - haxe bin/build-neko.hxml         && neko bin/Test.n
  - haxe bin/build-js.hxml           && node bin/Test.js
  - haxe bin/build-java.hxml         && java -jar bin/Test.jar
#  - haxe bin/build-cs.hxml           && mono bin/bin/Test.exe
  - haxe bin/build-cpp.hxml          && ./bin/Test
  - haxe bin/build-flash.hxml -D fdb && haxe flash/run.hxml bin/Test.swf
  - haxe bin/build-php.hxml          && php bin/index.php
  - haxe bin/build-python.hxml       && python3 bin/Test.py
